openapi: 3.0.3
info:
  title: 3scale CMS API
  version: '2.14'
  description: 3scale's undocumented content management system API
servers:
  - url: 'https://{tenant-name}-admin.{ocp-wildcard-url}'
    description: The base URL for a 3scale system-app admin route
    variables:
      tenant-name:
        default: 3scale
        description: The 3scale tenant to operate on
      ocp-wildcard-url:
        default: apps.your.openshift.example.com
        description: Wildcard URL used when installing 3scale
paths:
  /admin/api/cms/files.json:
    get:
      tags:
        - Files
      parameters:
        - name: page
          description: |
            The number for the page of results to retrieve, starting from page 1;
            defaults to 1
          schema:
            type: integer
            minimum: 1
            default: 1
          in: query
          required: false
        - name: per_page
          description: |
            The number of items to retrieve per page of results; defaults to 20
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          required: false
          in: query
        - name: section_id
          description: The section to query for files (hidden option in CMS API)
          schema:
            $ref: '#/components/schemas/SectionId'
          required: false
          in: query
      responses:
        '200':
          $ref: '#/components/responses/FileListResponse'
      operationId: list-files
      summary: List Files
      description: List files held within the 3scale CMS
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FileCreationRequest'
        required: true
      tags:
        - Files
      responses:
        '201':
          $ref: '#/components/responses/FileResponse'
        '422':
          $ref: '#/components/responses/ErrorListResponse'
        '500':
          $ref: '#/components/responses/ErrorHashResponse'
      operationId: create-file
      summary: Create File
      description: Create file within the 3scale CMS
  '/admin/api/cms/files/{file_id}.json':
    get:
      tags:
        - Files
      responses:
        '200':
          $ref: '#/components/responses/FileResponse'
      operationId: get-file
      summary: Get File
      description: Get a file descriptor
    put:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FileUpdatableFields'
        required: true
      tags:
        - Files
      responses:
        '200':
          $ref: '#/components/responses/FileResponse'
        '422':
          $ref: '#/components/responses/ErrorListResponse'
        '500':
          $ref: '#/components/responses/ErrorHashResponse'
      operationId: update-file
      summary: Update File
      description: Update an existing file
    delete:
      tags:
        - Files
      responses:
        '200':
          $ref: '#/components/responses/EmptyResponse'
      operationId: delete-file
      summary: Delete File
      description: Delete a file from 3scale CMS
    parameters:
      - name: file_id
        schema:
          $ref: '#/components/schemas/FileId'
        in: path
        required: true
  /admin/api/cms/sections.json:
    get:
      tags:
        - Sections
      parameters:
        - name: page
          description: |
            The number for the page of results to retrieve, starting from page 1;
            defaults to 1
          schema:
            type: integer
            minimum: 1
            default: 1
          in: query
          required: false
        - name: per_page
          description: |
            The number of items to retrieve per page of results; defaults to 20
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          required: false
          in: query
      responses:
        '200':
          $ref: '#/components/responses/SectionListResponse'
      operationId: list-sections
      summary: List Sections
      description: List sections held within the 3scale CMS
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SectionCreationRequest'
        required: true
      tags:
        - Sections
      responses:
        '201':
          $ref: '#/components/responses/SectionResponse'
        '422':
          $ref: '#/components/responses/ErrorListResponse'
        '500':
          $ref: '#/components/responses/ErrorHashResponse'
      operationId: create-section
      summary: Create Section
      description: Create section within the 3scale CMS
  '/admin/api/cms/sections/{section_id}.json':
    get:
      tags:
        - Sections
      responses:
        '200':
          $ref: '#/components/responses/SectionResponse'
      operationId: get-section
      summary: Get Section
      description: Get section descriptor
    put:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SectionUpdatableFields'
        required: true
      tags:
        - Sections
      responses:
        '200':
          $ref: '#/components/responses/SectionResponse'
        '422':
          $ref: '#/components/responses/ErrorListResponse'
        '500':
          $ref: '#/components/responses/ErrorHashResponse'
      operationId: update-section
      summary: Update Section
      description: Update section descriptor
    delete:
      tags:
        - Sections
      responses:
        '200':
          $ref: '#/components/responses/EmptyResponse'
        '423':
          $ref: '#/components/responses/EmptyResponse'
      operationId: delete-section
      summary: Delete Section
      description: Delete a section from 3scale CMS
    parameters:
      - name: section_id
        schema:
          $ref: '#/components/schemas/SectionId'
        in: path
        required: true
  '/admin/api/cms/sections/{system_name}.json':
    get:
      tags:
        - Sections
      responses:
        '200':
          $ref: '#/components/responses/SectionResponse'
      operationId: get-section-by-system-name
      summary: Get Section by System Name
      description: Get section descriptor
    put:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SectionUpdatableFields'
        required: true
      tags:
        - Sections
      responses:
        '200':
          $ref: '#/components/responses/SectionResponse'
        '422':
          $ref: '#/components/responses/ErrorListResponse'
        '500':
          $ref: '#/components/responses/ErrorHashResponse'
      operationId: update-section-by-system-name
      summary: Update Section by System Name
      description: Update section descriptor
    delete:
      tags:
        - Sections
      responses:
        '200':
          $ref: '#/components/responses/EmptyResponse'
      operationId: delete-section-by-system-name
      summary: Delete Section by System Name
      description: Delete a section from 3scale CMS
    parameters:
      - name: system_name
        schema:
          $ref: '#/components/schemas/SystemName'
        in: path
        required: true
  /admin/api/cms/templates.json:
    get:
      tags:
        - Templates
      parameters:
        - name: page
          description: |
            The number for the page of results to retrieve, starting from page 1;
            defaults to 1
          schema:
            type: integer
            minimum: 1
            default: 1
          in: query
          required: false
        - name: per_page
          description: |
            The number of items to retrieve per page of results; defaults to 20
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          required: false
          in: query
        - name: content
          description: |
            Whether to include the draft and published content in listed
            templates
          schema:
            type: boolean
          required: false
          in: query
      responses:
        '200':
          $ref: '#/components/responses/TemplateListResponse'
      operationId: list-templates
      summary: List Templates
      description: List all templates contained in the 3scale CMS
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TemplateCreationRequest'
        required: true
      tags:
        - Templates
      responses:
        '201':
          $ref: '#/components/responses/TemplateResponse'
        '422':
          $ref: '#/components/responses/ErrorListResponse'
        '500':
          $ref: '#/components/responses/ErrorHashResponse'
      operationId: create-template
      summary: Create Template
      description: Create template with the 3scale CMS
  '/admin/api/cms/templates/{template_id}.json':
    get:
      tags:
        - Templates
      responses:
        '200':
          $ref: '#/components/responses/TemplateResponse'
      operationId: get-template
      summary: Get Template
      description: |-
        Retrieve a template of any kind from 3scale (TODO: double-check response)
    put:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TemplateUpdatableFields'
        required: true
      tags:
        - Templates
      responses:
        '200':
          $ref: '#/components/responses/TemplateResponse'
        '422':
          $ref: '#/components/responses/ErrorListResponse'
        '500':
          $ref: '#/components/responses/ErrorHashResponse'
      operationId: update-template
      summary: Update Template
      description: 'Update a template draft (TODO: double-check response)'
    delete:
      tags:
        - Templates
      responses:
        '200':
          $ref: '#/components/responses/EmptyResponse'
      operationId: delete-template
      summary: Delete Template
      description: Delete a template from 3scale CMS
    parameters:
      - name: template_id
        schema:
          $ref: '#/components/schemas/TemplateId'
        in: path
        required: true
  '/admin/api/cms/templates/{template_id}/publish':
    put:
      tags:
        - Templates
      responses:
        '200':
          $ref: '#/components/responses/TemplateResponse'
      operationId: publish-template
      summary: Publish Template
      description: Move a template draft to be "published"
    parameters:
      - name: template_id
        schema:
          $ref: '#/components/schemas/TemplateId'
        in: path
        required: true
  /admin/api/provider.json:
    get:
      operationId: read-provider-settings
      summary: Read 3scale Provider Settings
      description: |
        Read 3scale Provider (Tenant) settings; particularly related to
        the developer portal.

        *Note:* This is technically part of the Account Management API, but is
        used to determine the location and access-token for retrieving file
        content, so it is tagged with `Files`.
      tags:
        - Files
      responses:
        '200':
          $ref: '#/components/responses/ProviderAccountResponse'
components:
  schemas:
    BuiltinPage:
      allOf:
        - $ref: '#/components/schemas/Template'
        - properties:
            path:
              type: string
              maxLength: 255
            hidden:
              type: boolean
            layout:
              type: string
              maxLength: 255
            title:
              type: string
              maxLength: 255
            system_name:
              $ref: '#/components/schemas/SystemName'
    BuiltinPartial:
      allOf:
        - $ref: '#/components/schemas/Template'
        - properties:
            system_name:
              $ref: '#/components/schemas/SystemName'
      example:
        id: 133
        type: builtin_partial
        created_at: 2022-03-05T04:48:29Z
        updated_at: 2022-03-05T04:48:29Z
        system_name: field
        content_type: text/html
        handler: null
        liquid_enabled: true
    EnumHandler:
      description: Handler type for rendering templates.
      type: string
      enum:
        - markdown
        - textile
      maxLength: 255
    EnumTemplateType:
      description: Type of `Template` for creation requests
      type: string
      enum:
        - page
        - layout
        - partial
    ErrorHash:
      description: Unhandled server error on 3scale
      properties:
        status:
          type: integer
        toXml:
          type: string
        error:
          type: string
    ErrorList:
      description: List of errors that occurred in processing a request
      type: array
      items:
        description: |
          Description of an individual error that occurred while processing
          an event.
        type: string
    File:
      description: File as held in the 3scale CMS
      allOf:
        - $ref: '#/components/schemas/FileUpdatableFields'
        - properties:
            id:
              $ref: '#/components/schemas/FileId'
            created_at:
              format: date-time
              description: The instant at which the file was first created in the 3scale CMS
              type: string
            updated_at:
              format: date-time
              description: The instant at which the file was last updated
              type: string
            url:
              description: The location at which the file is stored by 3scale; for 3scale-internal use
              type: string
            title:
              description: The name of the file
              type: string
      example:
        id: 9
        created_at: 2022-03-05T04:48:27Z
        updated_at: 2022-03-05T04:48:27Z
        section_id: 33
        path: /images/desk.jpg
        downloadable: false
        url: http://s3.openshift-storage.svc/bucket--99173774-11c4-4a63-9d1a-2df7b6a0b5bd/provider-name/2022/03/05/desk-b2a6c318d66334d2.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=VLXdr0R4TkaRNkgubbLx%2F20221005%2Fus-east-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20221005T214121Z&amp;X-Amz-Expires=900&amp;X-Amz-SignedHeaders=host&amp;X-Amz-Signature=aa05d76d599d07c6e8593a92edbe2d261aa6990326864d39465430b25761275e
        title: desk.jpg
        content_type: image/jpeg
    FileCreationRequest:
      required:
        - section_id
        - path
        - attachment
      allOf:
        - $ref: '#/components/schemas/FileUpdatableFields'
    FileId:
      description: Unique identifier for a `File` object
      type: integer
      format: int64
      example: '9'
    FileList:
      description: List of `File` objects
      type: object
      required:
        - collection
      properties:
        metadata:
          $ref: '#/components/schemas/ListPaginationMetadata'
        collection:
          type: array
          items:
            $ref: '#/components/schemas/File'
      example:
        - id: 9
          created_at: 2022-03-05T04:48:27Z
          updated_at: 2022-03-05T04:48:27Z
          section_id: 33
          path: /images/desk.jpg
          url: http://s3.openshift-storage.svc/bucket--99173774-11c4-4a63-9d1a-2df7b6a0b5bd/provider-name/2022/03/05/desk-b2a6c318d66334d2.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=VLXdr0R4TkaRNkgubbLx%2F20221005%2Fus-east-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20221005T214121Z&amp;X-Amz-Expires=900&amp;X-Amz-SignedHeaders=host&amp;X-Amz-Signature=aa05d76d599d07c6e8593a92edbe2d261aa6990326864d39465430b25761275e
          tag_list: ''
          title: desk.jpg
        - id: 10
          created_at: 2022-03-05T04:48:28Z
          updated_at: 2022-03-05T04:48:28Z
          section_id: 33
          path: /images/mouse.jpg
          url: http://s3.openshift-storage.svc/bucket--99173774-11c4-4a63-9d1a-2df7b6a0b5bd/provider-name/2022/03/05/mouse-54d77f30bdfb31a4.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=VLXdr0R4TkaRNkgubbLx%2F20221005%2Fus-east-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20221005T214121Z&amp;X-Amz-Expires=900&amp;X-Amz-SignedHeaders=host&amp;X-Amz-Signature=186eab31325093ec6b542ff9805621e6c1fa9a26bdfce24f7f9e446f22e635ca
          tag_list: ''
          title: mouse.jpg
    FileUpdatableFields:
      description: Fields that may be modified after file creation
      properties:
        section_id:
          $ref: '#/components/schemas/SectionId'
        path:
          description: |
            The path from which the file is retrieved from the 3scale Developer
            Portal. Must be unique across all CMS objects
          type: string
          maxLength: 255
        tag_list:
          description: Comma-separated list of tags
          type: string
        downloadable:
          description: |
            Flag indicating whether the file will be returned from the Developer
            Portal with headers indicating it is intended to be downloaded
          type: boolean
          default: false
        attachment:
          description: The full contents of the file
          type: string
          format: binary
        content_type:
          description: The mime-type describing type of content.
          type: string
    Layout:
      allOf:
        - $ref: '#/components/schemas/Template'
        - properties:
            system_name:
              $ref: '#/components/schemas/SystemName'
            title:
              description: Title for the layout
              type: string
      example:
        id: 119
        type: layout
        created_at: 2022-03-05T04:48:27Z
        updated_at: 2022-03-05T04:48:27Z
        system_name: main_layout
        content_type: text/html
        handler: null
        liquid_enabled: true
        title: Main Layout
    ListPaginationMetadata:
      properties:
        per_page:
          description: The number of items returned per page
          type: integer
        total_entries:
          description: The total number of items available
          type: integer
        total_pages:
          description: The total number of pages available
          type: integer
        current_page:
          description: The current page number, starting from 1
          type: integer
    Page:
      allOf:
        - $ref: '#/components/schemas/Template'
        - properties:
            path:
              description: |
                The path to which this template will be retrieved when browsing
                the developer portal
              type: string
              maxLength: 255
            hidden:
              type: boolean
            layout:
              type: string
              maxLength: 255
            title:
              type: string
              maxLength: 255
      example:
        id: 125
        type: page
        created_at: 2022-03-05T04:48:27Z
        updated_at: 2022-03-05T04:48:27Z
        title: 3scale_v2.js
        system_name: null
        path: /javascripts/3scale_v2.js
        hidden: false
        layout: null
        content_type: text/javascript
        handler: null
        liquid_enabled: null
    Partial:
      allOf:
        - $ref: '#/components/schemas/Template'
        - properties:
            system_name:
              $ref: '#/components/schemas/SystemName'
      example:
        id: 123
        type: partial
        created_at: 2022-03-05T04:48:27Z
        updated_at: 2022-03-05T04:48:27Z
        system_name: analytics
        content_type: text/html
        handler: null
        liquid_enabled: null
    ProviderAccount:
      description: >-
        Settings for the tenant (provider), including base URL and access code
        (if any) for the developer portal.
      type: object
      required:
        - id
        - created_at
        - updated_at
        - state
        - admin_domain
        - domain
        - admin_base_url
        - base_url
        - from_email
        - support_email
        - finance_support_email
        - site_access_code
        - organization_name
        - monthly_billing_enabled
        - monthly_charging_enabled
        - credit_card_stored
      properties:
        id:
          $ref: '#/components/schemas/ProviderAccountId'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        state:
          type: string
        admin_domain:
          type: string
        domain:
          type: string
        admin_base_url:
          type: string
        base_url:
          type: string
        from_email:
          type: string
        support_email:
          type: string
        finance_support_email:
          type: string
        site_access_code:
          type: string
          format: password
        organization_name:
          type: string
        monthly_billing_enabled:
          type: boolean
        monthly_charging_enabled:
          type: boolean
        credit_card_stored:
          type: boolean
      additionalProperties: true
      example:
        id: 2445581598751
        created_at: 2022-03-05T03:27:58Z
        updated_at: 2022-10-11T18:44:46Z
        admin_domain: 3scale-admin.apps.ocp.example.com
        domain: 3scale.apps.ocp.example.com
        admin_base_url: https://3scale-admin.apps.ocp.example.com
        base_url: https://3scale.apps.ocp.example.com
        from_email: no-reply@3scale.apps.ocp.example.com
        support_email: admin@3scale.apps.ocp.example.com
        finance_support_email: admin@3scale.apps.ocp.example.com
        site_access_code: abcd
        credit_card_stored: false
        monthly_billing_enabled: true
        monthly_charging_enabled: true
        state: approved
        links:
          - rel: users
            href: https://3scale-admin.apps.ocp.example.com/admin/api/accounts/2445581598751/users
        org_name: Sample Organization
        org_legaladdress: ''
        billing_address:
          company: Sample Organization
          address: ''
          address1: null
          address2: null
          phone_number: null
          city: null
          country: null
          state: null
          zip: null
        API_Purpose_3s__c: Company internal integration
        API_Status_3s__c: In design
        API_Onprem_3s__c: No, I'm only interested in SaaS
        Signup_origin: ''
    ProviderAccountId:
      type: integer
      format: int64
      example: '2'
    Section:
      description: Section within 3scale CMS
      allOf:
        - $ref: '#/components/schemas/SectionUpdatableFields'
        - properties:
            id:
              $ref: '#/components/schemas/SectionId'
            created_at:
              format: date-time
              type: string
            updated_at:
              format: date-time
              type: string
            partial_path:
              type: string
              maxLength: 255
            system_name:
              $ref: '#/components/schemas/SystemName'
      example:
        id: 30
        created_at: 2022-03-05T04:48:27Z
        updated_at: 2022-03-18T06:31:57Z
        title: Root
        system_name: root
        public: true
        parent_id: null
        partial_path: /
    SectionCreationRequest:
      description: Request fields for creation of Sections
      allOf:
        - $ref: '#/components/schemas/SectionUpdatableFields'
        - properties:
            partial_path:
              type: string
              maxLength: 255
            system_name:
              $ref: '#/components/schemas/SystemName'
    SectionId:
      description: Unique identifier for a `Section`
      type: integer
      format: int64
      example: '30'
    SectionList:
      description: List of `Section` objects
      type: object
      required:
        - collection
      properties:
        metadata:
          $ref: '#/components/schemas/ListPaginationMetadata'
        collection:
          type: array
          items:
            $ref: '#/components/schemas/Section'
      example:
        collection:
          - id: 30
            created_at: 2022-03-05T04:48:27Z
            updated_at: 2022-03-18T06:31:57Z
            title: Root
            system_name: root
            public: true
            parent_id: null
            partial_path: /
          - id: 31
            created_at: 2022-03-05T04:48:27Z
            updated_at: 2022-03-05T04:48:27Z
            title: javascripts
            system_name: javascripts
            public: true
            parent_id: 30
            partial_path: /javascripts
          - id: 32
            created_at: 2022-03-05T04:48:27Z
            updated_at: 2022-03-05T04:48:27Z
            title: css
            system_name: css
            public: true
            parent_id: 30
            partial_path: /css
          - id: 33
            created_at: 2022-03-05T04:48:27Z
            updated_at: 2022-03-05T04:48:27Z
            title: images
            system_name: images
            public: true
            parent_id: 30
            partial_path: /images
          - id: 34
            created_at: 2022-03-05T04:48:27Z
            updated_at: 2022-03-05T04:48:27Z
            title: Password
            system_name: password
            public: true
            parent_id: 30
            partial_path: /password
    SectionUpdatableFields:
      description: Fields that may be modified after section creation
      properties:
        public:
          description: Whether the section is viewable by users not logged in
          type: boolean
        title:
          description: |
            Title of the section; must be unique within parent section.
          type: string
          maxLength: 255
        parent_id:
          $ref: '#/components/schemas/SectionId'
    SystemName:
      description: Unique name for an object in 3scale CMS
      type: string
      maxLength: 255
    Template:
      description: Base type for all template types
      discriminator:
        propertyName: type
        mapping:
          builtin_page: '#/components/schemas/BuiltinPage'
          builtin_partial: '#/components/schemas/BuiltinPartial'
          layout: '#/components/schemas/Layout'
          page: '#/components/schemas/Page'
          partial: '#/components/schemas/Partial'
      properties:
        id:
          $ref: '#/components/schemas/TemplateId'
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
        content_type:
          description: |
            How the template should be described to web browsers with the
            Content-Type header
          type: string
          maxLength: 255
        handler:
          $ref: '#/components/schemas/EnumHandler'
        liquid_enabled:
          description: |
            Boolean flag to indicate whether the template should be populated
            by the Liquid templating system prior to rendering with `handler`
          type: boolean
        draft:
          description: |
            Full content of the template as held in draft mode. When published,
            this will be blank.
          type: string
          maxLength: 16777215
        published:
          description: Full content of the template as held in published mode.
          type: string
          maxLength: 16777215
    TemplateCreationRequest:
      required:
        - type
      allOf:
        - $ref: '#/components/schemas/TemplateUpdatableFields'
        - properties:
            type:
              $ref: '#/components/schemas/EnumTemplateType'
    TemplateId:
      type: integer
      format: int64
      example: '119'
    TemplateList:
      description: List of `Template` objects
      type: object
      required:
        - collection
      properties:
        collection:
          type: array
          items:
            $ref: '#/components/schemas/Template'
        metadata:
          $ref: '#/components/schemas/ListPaginationMetadata'
      example:
        collection:
          - id: 119
            type: layout
            created_at: 2022-03-05T04:48:27Z
            updated_at: 2022-03-05T04:48:27Z
            system_name: main_layout
            content_type: text/html
            handler: null
            liquid_enabled: true
            title: Main layout
          - id: 121
            type: page
            created_at: 2022-03-05T04:48:27Z
            updated_at: 2022-03-05T06:13:53Z
            title: Homepage
            system_name: null
            path: /
            hidden: false
            layout: main_layout
            content_type: text/html
            handler: null
            liquid_enabled: true
          - id: 123
            type: partial
            created_at: 2022-03-05T04:48:27Z
            updated_at: 2022-03-05T04:48:27Z
            system_name: analytics
            content_type: text/html
            handler: null
            liquid_enabled: null
        metadata:
          per_page: 20
          total_entries: 64
          total_pages: 4
          current_page: 1
    TemplateUpdatableFields:
      properties:
        system_name:
          $ref: '#/components/schemas/SystemName'
        title:
          type: string
          maxLength: 255
        path:
          type: string
          maxLength: 255
        draft:
          type: string
          maxLength: 16777215
        section_id:
          $ref: '#/components/schemas/SectionId'
        layout_name:
          type: string
        layout_id:
          $ref: '#/components/schemas/TemplateId'
        liquid_enabled:
          type: boolean
        handler:
          $ref: '#/components/schemas/EnumHandler'
        content_type:
          type: string
          maxLength: 255
    WrappedProviderAccount:
      description: Wrapper around objects of `ProviderAccount` type
      type: object
      required:
        - account
      properties:
        account:
          $ref: '#/components/schemas/ProviderAccount'
      example:
        account:
          id: 2445581598751
          created_at: 2022-03-05T03:27:58Z
          updated_at: 2022-10-11T18:44:46Z
          admin_domain: 3scale-admin.apps.ocp.example.com
          domain: 3scale.apps.ocp.example.com
          admin_base_url: https://3scale-admin.apps.ocp.example.com
          base_url: https://3scale.apps.ocp.example.com
          from_email: no-reply@3scale.apps.ocp.example.com
          support_email: admin@3scale.apps.ocp.example.com
          finance_support_email: admin@3scale.apps.ocp.example.com
          site_access_code: abcd
          credit_card_stored: false
          monthly_billing_enabled: true
          monthly_charging_enabled: true
          state: approved
          links:
            - rel: users
              href: https://3scale-admin.apps.ocp.example.com/admin/api/accounts/2445581598751/users
          org_name: Sample Organization
          org_legaladdress: ""
          billing_address:
            company: Sample Organization
            address: ""
            address1: null
            address2: null
            phone_number: null
            city: null
            country: null
            state: null
            zip: nul
          API_Purpose_3s__c: Company internal integration
          API_Status_3s__c: In design
          API_Onprem_3s__c: No, I'm only interested in SaaS
          Signup_origin: ""
  responses:
    EmptyResponse:
      description: Response with no body; eg, to indicate successful deletion
    ErrorHashResponse:
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorHash'
      description: Response containing an `ErrorHash`
    ErrorListResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorList'
      description: Response containing an `ErrorList`
    FileResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/File'
      description: Response containing a single file declaration
    FileListResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FileList'
      description: Response containing a list of `File`s
    ProviderAccountResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WrappedProviderAccount'
      description: Response containing the `WrappedProviderAccount` configuration
    SectionListResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SectionList'
      description: Response containing a list of `Section`s
    TemplateResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Template'
      description: Response containing a single `Template` of any kind
    TemplateListResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TemplateList'
      description: Response containing a list of templates of various kinds
    SectionResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Section'
      description: Response containing a single `Section`
  securitySchemes:
    provider_key:
      type: apiKey
      description: >-
        Provider API Key from the `Account Settings > Overview` page of a 3scale tenant.
        To view this key, a user must be logged in with `admin` privileges.
      name: provider_key
      in: query
    access_token:
      type: apiKey
      description: >-
        Access Token from the `Account Settings > Personal > Tokens` page of a 3scale tenant.
        The token must have access to both the `Account Management API` and the
        `Developer Portal API`.
      name: access_token
      in: query
security:
  - provider_key: [ ]
  - access_token: [ ]
tags:
  - name: Files
    description: Requests related specifically to files
  - name: Sections
    description: Requests related specifically to sections
  - name: Templates
    description: Requests related specifically to templates
